services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelchallenge_app
    container_name: laravelchallenge_app
    ports:
      - "8888:80"
    volumes:
      - ./project:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravelchallenge_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravelchallenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
